### ISSUE TITLE
[Feature] Jason Features SU24

### ISSUE THREAD

**Issue by OfekShaltiel-UTD** [UTDallasEPICS/Carson-s-Village#183]
**Feature Description**
All open Jason Features 

**Requirements**
## User List
- [x] #149 
## Donations
- [ ] #150 
## User Creation
- [ ] #143  Automatic phone number field.
- [x] #208

## SalesForce (Fall 2024)
- [ ] salesforce api integration? invite page should be just invite, not filling out profile info, another salesforce integration? 
- [ ] use SalesForce to automate large portions of page creation.

## page view
- [x] revisit layout (use existing as inpsiration)
 - [ ] Zooming animation for photos nice to have
## Workflow changes (duplicate to #184)
- [ ]  Better UX for Auth system
- [ ]  Some families do not want to receive donations through Stripe, so we need new frontend and backend changes to allow some users to opt out of onboarding onto Stripe. (Change invite page and page status)

**Comment by OfekShaltiel-UTD** [comment]
From Taz on the previous Jason issue
"- Resources – Goes to [[https://carsonsvillage.org/#](https://carsonsvillage.org/)](https://carsonsvillage.org/ "https://carsonsvillage.org/#"), needs to be https://carsonsvillage.org/resource-library/
    
- About us – should go to https://carsonsvillage.org/about-us/
    
- we will need to account for processing fees when displaying payouts - minus a %
- nav links open in new tab
    
- header needs to match 
    
- search with empty value should not do anything at all
    
- revisit page layouts again esp with different amounts of text
    
- search bar in nav may be extraneous?
    
- UX around donation vs message vs donation message - these are two different things, do we need to drop one? carsons site seems to do both as distinct entities
    
- ability to update profile info?
    
- family page or memorial page?
    
- instructions for using dropdown to list pages
    
- page name => person name
    
- instructions around family creation - yes, create the family, assign the page to it
    
- instructions around profile picture select - maybe just rework this UX
    
- datepicker may be borked
    
- locationdoes not show up
    
- image CSS - fix stretching
    
- message form reset on submit
    
- users list needs to be actual user management
    
- double check admin invite
    
- family create UI needs to distinguish between family info vs info for inviting the first user - clarity around users vs families vs pages
    
- no page id in transaction list
    
- clarity around how funds distribution works - this is the payout from stripe to the family account
    
- clarity around how advocates are assigned to families - im the one that created the family and invited jason, so i show up
    
- goal date being reached doesnt trigger anything - manual toggle of archiving. need way to see archived/unarchived and unarchiving."

**Comment by AlonsoToji** [comment]
Comments based off of the Jason's document review:
 - pictures are offset when the user zooms out
 - make sure the header of the pages match
 - possibly remove the address from the admin profile page
 - when showing creation date and donation deadline on the PAGES page, remove the time and leave just the date
 - add an indicator if a page has been archived
 - add an option to include more than 1 picture
 - have access to edit the comments (from new page, personal information, and the little "?")
 - instead of having date of birth, change it to just the person's age
 - separate location into name of funeral home and address
 -  fix the save button
 - do something with the comment moderation section 
 - have an option to hide donation goals
 - why does clicking VIEW takes the user to the PAGES tab?
 - do we need to capture the user's address
 - on the family creation page, we could remove middle name, phone, and address, and save doesn't do anything
 - is the family creation page the entity that will hold the family page, in the event that a family has more than one?
 - why is the family reports page blank?
 - why is the donations page pretty much blank?
